name: Build, Dockerize and Push to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Test_12345!?  
          MYSQL_DATABASE: videothek
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h 127.0.0.1 -u root -pTest_12345!? -e "SHOW TABLES IN videothek"; do
          echo "Waiting for MySQL..."
          sleep 30
        done

    - name: Set environment variables
      run: |
        echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/videothek" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_USERNAME=root" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_PASSWORD=Test_12345!?" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image for app
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/app-repository:latest

    - name: Push Docker image for app
      run: |
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/app-repository:latest

    - name: Build Docker image for MySQL
      run: |
        docker build . --file Dockerfile.mysql --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/mysql-repository:latest

    - name: Push Docker image for MySQL
      run: |
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/mysql-repository:latest
